name = "sofiakissite"
account_id = 7d9f45f8ee719e4240acd7cf354acc47
compatibility_date = "2026-02-22"
pages_build_output_dir = "public"

# =====================================
# DEVELOPMENT ENVIRONMENT VARIABLES
# =====================================
[vars]
APP_ENV = "development"

[[d1_databases]]
binding = "CORE_DB"
database_name = "campaign-core-db-dev"
database_id = "c87df1e0-4523-493f-af98-ddefb874969f"

# =====================================
# PRODUCTION ENVIRONMENT VARIABLES
# =====================================
[env.production]

[[env.production.d1_databases]]
binding = "CORE_DB"
database_name = "campaign-core-db"
database_id = "01783e07-91bc-4482-8be7-6112cf909c14"

